# SPDX-FileCopyrightText: 2022 Nerves Project Developers
#
# SPDX-License-Identifier: Apache-2.0

all: check

check:
	cd heart_test && mix deps.get && mix test

clean:
	cd heart_test && mix clean

.PHONY: all check clean
